version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: example
    volumes:
      - ./init-example.js:/docker-entrypoint-initdb.d/init-example.js:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    ports:
      - "8888:8888"
    depends_on:
      - mongo
